Atualizar readme e versoes
betrybe/sd-0x-cookmaster-v2 pull request #10
Opened 2021-03-02 12:27 UTC by LucasSGomide

2021-03-03 18:02 UTC, renatosousafilho commented on README.md
> +  - [Tabelas](#tabelas)
@LucasSGomide acho interessantem manter Coleção pois como o projeto usa mongodb acaba sendo o termo mais apropriado

2021-03-03 18:06 UTC, renatosousafilho commented
Muito boa a dica. 

Acho que vale aproveitar o PR para fazer uma mudança. Recebemos um feedback em relação ao uso da imagem do Erick Jackquin no README e apresentação do projeto, por se tratar de uma pessoa envolvida em polêmicas. Seria legal substituir por algum exemplo de pessoa que não vá de contra aos valores da Trybe. Se tiver uma sugestão, na T6 eu usei como o exemplo o Chefe Sueco do Muppets, mas se tiver qualquer outra sugestão, é bem vinda.

2021-03-03 18:10 UTC, brunobatista25 commented
opa @renatosousafilho podemos alterar sim, @LucasSGomide pode alterar pra gente isso?

2021-03-04 17:48 UTC, renatosousafilho commented
@LucasSGomide Lucas, se não for te agarra muito você pode substituir as referências do Erick Jackquin por algum exemplo, pode usar tipo Ana Maria Braga. Se você tiver muito ocupado, pode seguir em frente que eu faço essa alteração depois.

2021-03-04 17:48 UTC, renatosousafilho approved these changes

2021-03-07 19:32 UTC, brunobatista25 requested changes

2021-03-07 19:32 UTC, brunobatista25 commented on README.md
> +Link: [FORMULÁRIO DE AVALIAÇÃO DE PROJETO](https://bit.ly/2OfLJPn)
```suggestion
Link: [FORMULÁRIO DE AVALIAÇÃO DE PROJETO](https://be-trybe.typeform.com/to/ZTeR4IbH)
```

2021-03-11 16:46 UTC, merged